version: '3'

services:
  db:
    image: postgres
    env_file: dev.env
    volumes:
      - pg_data/:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - ./tcls/:/app
      - D:/git/owl-vodchat-downloader/chatlogs:/chatlogs
      - data/:/data
    ports:
      - "8000:8000"
    env_file: dev.env
    depends_on:
      - db
volumes:
  pg_data:
  data: