version: '3'

services:
  db:
    container_name: tcls_db
    image: postgres
    env_file: dev.env
    volumes:
      - pg_data/:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:alpine
  web:
    container_name: tcls
    build: .
    command: python3 manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - ./tcls/:/app
      - chatlogs/:/chatlogs
    ports:
      - "8000:8000"
    env_file: dev.env
    depends_on:
      - db
      - redis
  web_worker:
    container_name: web_worker
    image: tcls-app_web
    command: celery -A tcls worker -l info
    volumes:
      - ./tcls/:/app
    env_file: dev.env
    depends_on:
      - db
      - redis
  vod_worker:
    container_name: vod_worker
    build: vod_downloader/.
    command: celery -A vod_downloader worker -l info -Q vod_queue --max-memory-per-child 300000 --max-tasks-per-child 2
    volumes:
      - ./vod_downloader/:/app
      - chatlogs/:/chatlogs
    depends_on:
      - redis
  flower:
    container_name: flower
    image: mher/flower
    command: ['flower', '--broker=redis://redis:6379/0', '--port=8001']
    ports:
      - 8001:8001
    depends_on:
      - vod_worker
      - web_worker

volumes:
  pg_data:
  chatlogs: