version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_data/:/var/lib/postgres/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tcls/:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
volumes:
  pg_data: