version: '3'

services:
  db:
    container_name: tcls_db
    image: postgres
    env_file: dev.env
    volumes:
      - pg_data/:/var/lib/postgresql/data
  # vod_downloader:
  #   container_name: tcls_vd
  #   build: './vod_downloader'
  #   env_file: vod_downloader/vod_downloader.env
  #   volumes:
  #     - chatlogs/:/chatlogs
  redis:
    image: redis:alpine
  web:
    container_name: tcls
    build: .
    command: python3 manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - ./tcls/:/app
      - chatlogs/:/chatlogs
    ports:
      - "8000:8000"
    env_file: dev.env
    depends_on:
      - db
      - redis
  web_worker:
    container_name: web_worker
    image: tcls-app_web
    command: celery -A tcls worker -l info
    volumes:
      - ./tcls/:/app
    env_file: dev.env
    depends_on:
      - db
      - redis
  vod_worker:
    container_name: vod_worker
    build: vod_downloader/.
    command: celery -A vod_downloader worker -l debug -Q vod_queue
    volumes:
      - ./vod_downloader/:/app
      - chatlogs/:/chatlogs
    depends_on:
      - redis

volumes:
  pg_data:
  chatlogs: