# Generated by Django 2.1.7 on 2019-03-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcomment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
