# Generated by Django 2.1.7 on 2019-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190302_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcomment',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
