# Generated by Django 2.1.7 on 2019-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190302_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='video_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
