# Generated by Django 2.1.7 on 2019-03-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logfile_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcomment',
            name='time',
            field=models.DurationField(blank=True),
        ),
    ]
