# Generated by Django 2.1.7 on 2019-03-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190303_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='raw_data',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
