# Generated by Django 2.1.7 on 2019-03-23 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190316_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='video_id',
        ),
        migrations.AddField(
            model_name='logfile',
            name='video',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Video'),
            preserve_default=False,
        ),
    ]
