# Generated by Django 2.1.7 on 2019-03-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190323_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
